/*
 * adc.h
 *
 *  Created on: Jul 17, 2025
 *      Author: riginel
 */

#ifndef INCLUDE_ADC_ADC_H_
#define INCLUDE_ADC_ADC_H_

#define Y_AXIS_PORT  GPIO_PORT_P4
#define Y_AXIS_PIN  GPIO_PIN4
#define Y_AXIS_MEM ADC_MEM0
#define Y_AXIS_INPUT ADC_INPUT_A9

#define X_AXIS_PORT GPIO_PORT_P6
#define X_AXIS_PIN GPIO_PIN0
#define X_AXIS_MEM ADC_MEM1
#define X_AXIS_INPUT ADC_INPUT_A15

#define AIR_SENSOR_PORT GPIO_PORT_P4
#define AIR_SENSOR_PIN  GPIO_PIN3
#define AIR_SENSOR_MEM  ADC_MEM2
#define AIR_SENSOR_INPUT ADC_INPUT_A10

#define TANK_SENSOR_PORT GPIO_PORT_P5
#define TANK_SENSOR_PIN GPIO_PIN4
#define TANK_SENSOR_MEM ADC_MEM3
#define TANK_SENSOR_INPUT ADC_INPUT_A0

#define RESERVOIRE_SENSOR_PORT GPIO_PORT_P5
#define RESERVOIRE_SENSOR_PIN GPIO_PIN5
#define RESERVOIRE_SENSOR_MEM ADC_MEM4
#define RESERVOIRE_SENSOR_INPUT ADC_INPUT_A1


void adc_init();




#endif /* INCLUDE_ADC_ADC_H_ */
